# netlify.toml
[build]
  publish = "./"                # ton dossier public (ex: "./" ou "public")
  command = "node build-version.js && echo 'Build terminé 🚀'"

# Variables d'environnement automatiques (optionnel)
[build.environment]
  NODE_VERSION = "18"

# Activer les headers HTTP modernes (recommandé pour PWA)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
